# Generated by Django 4.0.4 on 2024-02-21 08:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_column='STATUS', default='Draft', max_length=100)),
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('vessel', models.CharField(blank=True, db_column='VESSEL', max_length=255, null=True)),
                ('bl_date', models.DateField(blank=True, db_column='BL_DATE', null=True)),
                ('load_port', models.CharField(blank=True, db_column='LOAD_PORT', max_length=255, null=True)),
                ('discharge_port', models.CharField(blank=True, db_column='DISCHARGE_PORT', max_length=255, null=True)),
                ('turn_time_hours', models.FloatField(db_column='TURN_TIME_HOURS')),
                ('cargo', models.CharField(blank=True, db_column='CARGO', max_length=255, null=True)),
                ('shipper_supplier', models.CharField(blank=True, db_column='SHIPPER_SUPPLIER', max_length=255, null=True)),
                ('demurrage_rate_per_day', models.DecimalField(db_column='DEMURRAGE_RATE_PER_DAY', decimal_places=2, max_digits=10)),
                ('despatch_rate_per_day', models.DecimalField(db_column='DESPATCH_RATE_PER_DAY', decimal_places=2, max_digits=10)),
                ('cargo_qty', models.FloatField(db_column='CARGO_QTY')),
                ('discharge_rate', models.FloatField(db_column='DISCHARGE_RATE')),
                ('allowed_time', models.FloatField(db_column='ALLOWED_TIME')),
                ('charter_type', models.CharField(blank=True, db_column='CHARTER_TYPE', max_length=255, null=True)),
                ('receiver_buyer', models.CharField(blank=True, db_column='RECEIVER_BUYER', max_length=255, null=True)),
                ('nor_tendered', models.DateTimeField(db_column='NOR_TENDERED')),
                ('commenced_loading_time', models.DateTimeField(db_column='COMMENCED_LOADING_TIME')),
                ('completed_loading_time', models.DateTimeField(db_column='COMPLETED_LOADING_TIME')),
            ],
            options={
                'db_table': 'SHIPPING_DETAIL',
            },
        ),
        migrations.CreateModel(
            name='SplitQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_column='STATUS', default='Draft', max_length=100)),
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('port_name', models.CharField(db_column='PORT_NAME', max_length=255)),
                ('cargo_quantity', models.FloatField(db_column='CARGO_QUANTITY', default=0.0)),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, max_digits=10)),
                ('remaining_cargo_qty', models.FloatField(blank=True, db_column='REMAINING_CARGO_QUANTITY', default=0.0, null=True)),
                ('shipping_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_quantities', to='masters.shippingdetail')),
            ],
            options={
                'db_table': 'SPLIT_QUANTITY',
            },
        ),
        migrations.CreateModel(
            name='ShippingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_column='STATUS', default='Draft', max_length=100)),
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('count', models.BooleanField(db_column='COUNT')),
                ('stage_name', models.CharField(db_column='STAGE_NAME', max_length=255)),
                ('start_date_time', models.DateTimeField(db_column='START_DATE_TIME')),
                ('end_date_time', models.DateTimeField(db_column='END_DATE_TIME')),
                ('percentage', models.PositiveSmallIntegerField(db_column='PERCENTAGE', default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('shipping_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='masters.shippingdetail')),
            ],
            options={
                'db_table': 'SHIPPING_STAGE',
            },
        ),
        migrations.CreateModel(
            name='LayTimeCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_column='STATUS', default='Draft', max_length=100)),
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, max_digits=10)),
                ('actual_time', models.FloatField(blank=True, db_column='ACTUAL_TIME', default=1703823476.82923, null=True)),
                ('allowed_time', models.FloatField(db_column='ALLOWED_TIME')),
                ('total_time_difference', models.FloatField(db_column='TOTAL_TIME_DIFFERENCE')),
                ('is_time_saved', models.BooleanField(db_column='IS_TIME_SAVED')),
                ('shipping_detail', models.OneToOneField(blank=True, db_column='SHIPPING_DETAIL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laytime_calculator', to='masters.shippingdetail')),
            ],
            options={
                'db_table': 'LAYTIME_CALCULATOR',
            },
        ),
    ]
