# Generated by Django 4.0.4 on 2024-03-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingstage',
            name='shipping_detail',
        ),
        migrations.RemoveField(
            model_name='splitquantity',
            name='shipping_detail',
        ),
        migrations.DeleteModel(
            name='LayTimeCalculator',
        ),
        migrations.DeleteModel(
            name='ShippingDetail',
        ),
        migrations.DeleteModel(
            name='ShippingStage',
        ),
        migrations.DeleteModel(
            name='SplitQuantity',
        ),
    ]
