# Generated by Django 4.0.4 on 2024-03-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_remove_shippingstage_shipping_detail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MstBRMStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_column='STATUS', default='Draft', max_length=100)),
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('material_ref', models.CharField(blank=True, db_column='MATERIAL_REF', max_length=200, null=True)),
                ('raw_report', models.CharField(blank=True, db_column='RAW_REPORT', max_length=500, null=True)),
                ('material', models.CharField(blank=True, db_column='MATERIAL', max_length=200, null=True)),
                ('rwb', models.CharField(blank=True, db_column='RWB', max_length=200, null=True)),
                ('total_stock_name', models.CharField(blank=True, db_column='TOTAL_STOCK_NAME', max_length=200, null=True)),
                ('ground_stock', models.IntegerField(blank=True, db_column='GROUND_STOCK', null=True)),
            ],
            options={
                'db_table': 'MST_BRM_STOCK',
            },
        ),
        migrations.CreateModel(
            name='MstBRMStockOtherLoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_column='STATUS', default='Draft', max_length=100)),
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('material_ref', models.CharField(blank=True, db_column='MATERIAL_REF', max_length=200, null=True)),
                ('unit', models.CharField(blank=True, db_column='UNIT', max_length=100, null=True)),
                ('dabuna', models.IntegerField(blank=True, db_column='DABUNA', null=True)),
                ('paradeep', models.IntegerField(blank=True, db_column='PARADEEP', null=True)),
                ('kirandul', models.IntegerField(blank=True, db_column='KIRANDUL', null=True)),
                ('vizag', models.IntegerField(blank=True, db_column='VIZAG', null=True)),
            ],
            options={
                'db_table': 'MST_BRM_STOCK_OTHER_LOC',
            },
        ),
        migrations.CreateModel(
            name='MstBRMTargetSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_column='STATUS', default='Draft', max_length=100)),
                ('is_approved', models.BooleanField(db_column='IS_APPROVED', default=False)),
                ('is_active', models.BooleanField(blank=True, db_column='IS_ACTIVE', default=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, db_column='IS_DELETED', default=False, null=True)),
                ('created_by', models.CharField(blank=True, db_column='CREATED_BY', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CREATED_DATE')),
                ('last_updated_by', models.CharField(blank=True, db_column='LAST_UPDATED_BY', max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_column='LAST_UPDATED_DATE')),
                ('vessel', models.CharField(db_column='VESSEL', max_length=100)),
                ('cargo', models.CharField(blank=True, db_column='CARGO', max_length=100, null=True)),
                ('source_port', models.CharField(blank=True, db_column='SOURCE_PORT', max_length=200, null=True)),
                ('discharge_port', models.CharField(blank=True, db_column='DISCHARGE_PORT', max_length=200, null=True)),
                ('qty', models.IntegerField(blank=True, db_column='QTY', null=True)),
                ('loadport_date', models.CharField(blank=True, db_column='LOADPORT_DATE', max_length=200, null=True)),
                ('arrival', models.DateField(blank=True, db_column='ARRIVAL', null=True)),
                ('today_position', models.CharField(blank=True, db_column='TODAY_POSITION', max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, db_column='REMARKS', max_length=500, null=True)),
                ('dem', models.FloatField(blank=True, db_column='DEM', null=True)),
                ('discharge_rate_berth', models.FloatField(blank=True, db_column='DISCHARGE_RATE_BERTH', null=True)),
                ('shared_cargo', models.CharField(blank=True, db_column='SHARED_CARGO', default='N', max_length=10, null=True)),
                ('stage', models.CharField(blank=True, db_column='STAGE', max_length=200, null=True)),
                ('con_or_tbn', models.CharField(blank=True, max_length=200, null=True, verbose_name='CON_OR_TBN')),
                ('material_n_lp', models.CharField(blank=True, max_length=500, null=True, verbose_name='MATERIAL_N_LP')),
                ('vessel_cargo_arrival', models.CharField(blank=True, db_column='VESSEL_CARGO_ARRIVAL', max_length=200, null=True)),
                ('major', models.CharField(blank=True, db_column='MAJOR', default='Y', max_length=10, null=True)),
                ('material_ref', models.CharField(blank=True, db_column='MATERIAL_REF', max_length=200, null=True)),
                ('material', models.CharField(blank=True, db_column='MATERIAL', max_length=200, null=True)),
                ('rwb', models.CharField(blank=True, db_column='RWB', max_length=200, null=True)),
                ('ground_stock', models.IntegerField(blank=True, db_column='GROUND_STOCK', null=True)),
            ],
            options={
                'db_table': 'MST_BRM_TARGET_SHEET',
            },
        ),
    ]
