# Generated by Django 4.0.4 on 2024-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laytime_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingstage',
            name='count',
            field=models.BooleanField(db_column='COUNT', default=False),
        ),
    ]
