# Generated by Django 4.0.4 on 2024-04-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laytime_details', '0003_shippingdetail_demurrage_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetail',
            name='demurrage_reason',
        ),
        migrations.AddField(
            model_name='shippingdetail',
            name='remarks',
            field=models.CharField(blank=True, db_column='REMARKS', max_length=255, null=True),
        ),
    ]
