# Generated by Django 4.0.4 on 2024-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laytime_details', '0004_remove_shippingdetail_demurrage_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingdetail',
            name='remarks',
            field=models.CharField(blank=True, db_column='REMARKS', max_length=2000, null=True),
        ),
    ]
