# Generated by Django 4.0.4 on 2024-04-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laytime_details', '0005_alter_shippingdetail_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetail',
            name='rate_type',
            field=models.FloatField(blank=True, db_column='RATE_TYPE', null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='commenced_loading_time',
            field=models.DateTimeField(db_column='COMMENCED_TIME'),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='completed_loading_time',
            field=models.DateTimeField(db_column='COMPLETED_TIME'),
        ),
    ]
