# Generated by Django 4.0.4 on 2024-05-20 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laytime_details', '0007_alter_shippingdetail_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laytimecalculator',
            name='amount',
            field=models.FloatField(db_column='AMOUNT'),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='cargo',
            field=models.CharField(blank=True, db_column='CARGO', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='cargo_qty',
            field=models.FloatField(db_column='CARGO_QTY', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='charter_type',
            field=models.CharField(blank=True, db_column='CHARTER_TYPE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='discharge_port',
            field=models.CharField(blank=True, db_column='DISCHARGE_PORT', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='load_port',
            field=models.CharField(blank=True, db_column='LOAD_PORT', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='rate_type',
            field=models.CharField(choices=[('loading', 'loading'), ('discharge', 'discharge')], db_column='RATE_TYPE', max_length=20),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='receiver_buyer',
            field=models.CharField(blank=True, db_column='RECEIVER_BUYER', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='remarks',
            field=models.CharField(blank=True, db_column='REMARKS', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='shipper_supplier',
            field=models.CharField(blank=True, db_column='SHIPPER_SUPPLIER', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetail',
            name='vessel',
            field=models.CharField(blank=True, db_column='VESSEL', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='splitquantity',
            name='amount',
            field=models.FloatField(db_column='AMOUNT'),
        ),
        migrations.AlterField(
            model_name='splitquantity',
            name='port_name',
            field=models.CharField(db_column='PORT_NAME', max_length=100),
        ),
    ]
