# C:\Users\shali\Documents\shalin\test-app\laytime_calculator\settings.py

"""
Django settings for laytime_calculator project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9t25jai&9k2k_6-%ueo+4iv_hwblwqw(s4_5$^a3%iv67__8af'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CSRF_TRUSTED_ORIGINS = ["https://*.myamns.in", "https://*.amns.in", 'http://localhost:3000']

#YOUR PREFIX will be same as we have defined `REACT_APP_TOKEN_PREFIX` in `.env` file of our frontend
CSRF_COOKIE_NAME = 'LAYTIME_UAT_API-csrftoken'
SESSION_COOKIE_NAME = 'LAYTIME_UAT_API-sessionid'

CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_HTTPONLY = False
SESSION_COOKIE_AGE = 14400

# Application definition

DEPENDENCY_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_swagger',
    'reversion',
    'multiselectfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    'rbac',
    'workflow',
    'api',
]

PROJECT_APPS = [
    'laytime_details',
    'masters'
    # 'finance',
]

INSTALLED_APPS = DEPENDENCY_APPS + PROJECT_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'approval-authorization',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'req',
    'source'
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'laytime_calculator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'laytime_calculator.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'laytime_db',
        'USER': 'postgres',
        'PASSWORD': '12345678',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],

    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser'
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ],
    'DEFAULT_METADATA_CLASS': 'api.metadata.MinimalMetadata',

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema'
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = []
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MODEL_VALIDATORS = {}

DISPLAY_MODELS = {
    # Models that will be displayed on Screen
    'grncreationuttam': 'GRN_CREATION_UTTAM',
    'grncreationsto': 'GRN_CREATION_STO',
    'porequestuttam': 'PO_REQUEST_UTTAM',
    'uttampocommercialchart': 'UTTAM_PO_COMMERCIAL_CHART',
    'uttamproductmapping': 'UTTAM_PRODUCT_MAPPING',
    'mstbrmstock': 'BRM Stock',
    'mstbrmstockotherloc': 'BRM Stock Other Loc',
    'mstbrmtargetsheet': 'BRM Target Sheet',
}

DISPLAY_MODEL_FIELDS = {
    'grncreationuttam': ['id', 'gst_invoice', 'invoice_date', 'batch', 'received_date', 'transporter_name',
                         'vehicle_no', 'lr_no', 'gate_no', 'rj_number'],
    'grncreationsto': ['id', 'gst_invoice', 'invoice_date', 'batch', 'transporter_name', 'vehicle_no', 'lr_no', 'batch',
                       'gate_no'],
    'porequestuttam': ['id', 'coil_id', 'reference_number', 'monogram', 'ink_jet_printing', 'grade',
                       'product', 'material_code', 'hr_thickness', 'hr_width', 'finish_thickness',
                       'finish_width', 'zinc_coating', 'coil_weight', 'spangle_type', 'top_color_name',
                       'back_coat', 'fg_equivalent_specs', 'qty'],
    'uttampocommercialchart': ['id', 'product', 'finish_thickness', 'rate'],
    'uttamproductmapping': ['id', 'product', 'commercial_product'],
    'mstbrmstock': ['id', 'material_ref', 'raw_report', 'material', 'rwb', 'total_stock_name', 'ground_stock'],
    'mstbrmstockotherloc': ['id', 'material_ref', 'unit', 'dabuna', 'paradeep', 'kirandul', 'vizag'],
    'mstbrmtargetsheet': ['id', 'vessel','cargo','source_port','discharge_port','qty','loadport_date','arrival',
                          'today_position','remarks','dem','discharge_rate_berth','shared_cargo','stage',
                          'con_or_tbn','material_n_lp','vessel_cargo_arrival','major','material_ref','material','rwb','ground_stock',],
    'shippingdetail': ['status', 'id', 'vessel', 'bl_date', 'load_port', 'discharge_port', 'turn_time_hours', 'cargo', 'shipper_supplier', 
                       'demurrage_rate_per_day', 'despatch_rate_per_day', 'cargo_qty', 'discharge_rate', 'allowed_time', 'charter_type', 
                       'receiver_buyer', 'nor_tendered', 'commenced_loading_time', 'completed_loading_time'],
    'workflowtransactions': ['action']
}

AUTO_GENERATION_SECTIONS = ['MASTERS', 'FINANCE']

EXTRA_USER_META = {
    'MASTERS': [
        {
            'app': 'masters',
            'title': 'MASTER'
        }
    ],
    'APPROVALS': [
        {
            "screen": "LaytimeApprovals",
            "type": "subsection",
            "title": "Laytime Approvals",
        },
    ],
    'LAYTIME': [
        {
            "screen": "LaytimeCalculator",
            "type": "subsection",
            "title": "Laytime Calculator"
        },
    ],
    'Dashboard': [
        {
            "screen": "Dashboard",
            "type": "subsection",
            "title": "Dashboard"
        }
    ]
}

SECTION_ICONS = {
    'MASTERS': 'TableOutlined',
    'FORMS': 'TableOutlined',
    'Dashboard': 'TableOutlined',
    'APPROVALS': 'TableOutlined',
    'LAYTIME': 'TableOutlined',
    # 'FINANCE': 'fa fa-th-list'
}

URL_METADATA_CLASS = {
    'api': 'api.metadata.ApiMetadata',
    'User': 'rbac.metadata.RbacMetadata',
    'Suggest': 'rbac.metadata.RbacMetadata',
    'Group': 'rbac.metadata.RbacMetadata',
    'Permission': 'rbac.metadata.RbacMetadata',
}

MODEL_FIELD_CHOICES = {
}

MASTERS_APP_RBAC = 'masters'

APPLY_SEARCH_MODEL_FIELDS = {
    'grncreationuttam': ['gst_invoice', 'invoice_date','batch', 'received_date', 'transporter_name',
                         'vehicle_no', 'lr_no', 'gate_no', 'rj_number'],
    'grncreationsto': ['gst_invoice', 'invoice_date', 'batch', 'transporter_name', 'vehicle_no', 'lr_no',
                       'gate_no'],
    'porequestuttam': ['coil_id', 'reference_number','product', 'material_code',
                       'hr_thickness', 'hr_width', 'finish_thickness','finish_width'],
    'uttampocommercialchart': ['product', 'finish_thickness'],
    'uttamproductmapping': ['product', 'commercial_product'],
    'mstbrmstock': ['id', 'material_ref', 'raw_report', 'material', 'rwb', 'total_stock_name', 'ground_stock'],
    'mstbrmstockotherloc': ['id', 'material_ref', 'unit', 'dabuna', 'paradeep', 'kirandul', 'vizag'],
    'mstbrmtargetsheet': ['id', 'vessel','cargo','source_port','discharge_port','qty','loadport_date','arrival',
                          'today_position','remarks','dem','discharge_rate_berth','shared_cargo','stage',
                          'con_or_tbn','material_n_lp','vessel_cargo_arrival','major','material_ref','material','rwb','ground_stock',],
    'shippingdetail': ['id', 'status', 'vessel', 'bl_date', 'load_port', 'discharge_port', 'turn_time_hours', 'cargo', 'shipper_supplier', 
                       'demurrage_rate_per_day', 'despatch_rate_per_day', 'cargo_qty', 'discharge_rate', 'allowed_time', 'charter_type', 
                       'receiver_buyer', 'nor_tendered', 'commenced_loading_time', 'completed_loading_time', 'rate_type',
                       'laytime_calculator__is_time_saved','laytime_calculator__amount','laytime_calculator__total_time_difference',
                       'laytime_calculator__actual_time','laytime_calculator__allowed_time', 'stages__stage_name', 'stages__start_date_time',
                       'stages__end_date_time', 'stages__percentage', 'split_quantities__port_name', 'split_quantities__cargo_quantity', 
                       'split_quantities__amount'],
}

FOREIGN_KEY_UI_NAME_MAP = {
     'balanceconfirmation': {
         'location': [
             {
                 'field': 'location__location_name',
                 'type': 'text'
             }
         ],
     },
     'shippingdetail': {
         'laytime_calculator': [
             {
                 'field': 'laytime_calculator__amount',
                 'type': 'text'
             },
             {
                 'field': 'laytime_calculator__total_time_difference',
                 'type': 'text'
             },
             {
                 'field': 'laytime_calculator__actual_time',
                 'type': 'text'
             },
             {
                 'field': 'laytime_calculator__allowed_time',
                 'type': 'text'
             },
         ],
     },
}

MEDIA_ROOT = BASE_DIR + '/media/'
MEDIA_URL = '/media/'
X_FRAME_OPTIONS = 'SAMEORIGIN'

WORKFLOW_EMAIL_POLICY = {
    'default': {
        'Init': {
            'request': 'workflow.email_policy.notify_next_level',
        },
        'Approve': {
            'request': 'workflow.email_policy.notify_next_level',
            'notification': 'workflow.email_policy.get_request_initiator'
        },
        'Reject': {
            'notification': 'workflow.email_policy.notify_the_hierarchy'
        },
    }
}

RABBITMQ_CONF = {
    "RABBITMQ_CON_URL": "",
    "RABBITMQ_QUEUE": "",
    "SENDER_MAIL": "",
    "MAIL_CREDENTIALS": {"sender_email": "", "mailserver": ""}
}

WORKFLOW_MAIL_MAP = {

}

MODELS_WITH_MAIL_APPROVAL = []

LANDING_PAGE_FMT = "http://localhost:3000/app/ApprovalForm/{}"

APPROVAL_API_URLS = {
    'shippingdetail': ''
}

# APPROVAL_GROUPS = []

MASTERS_APP_NAME = 'masters'

DATE_INPUT_FORMAT = ['%d-%m-%Y']

DATE_TIME_INPUT_FORMAT = ['iso-8601']

TIME_INPUT_FORMAT = []

POST_SAVE_OBJ_RETURN_HOOKS = {
}

CHECK_USER_REGISTRATION = True

USER_PROFILE_MODEL_DETAILS = {
    'app': 'masters',
    'model': 'UserProfile',
    'search_on_field': 'outlook_id'
}

USER_PROFILE_SERIALIZER = 'masters.serializers.UserProfileSerializer'

DATA_RESTRICT_PERMISSIONS = {}

MASTER_FILES_MOSS_UPLOAD = False
MOSS_BASE_URL = ''
MOSS_USERNAME = ''
MOSS_PASSWORD = ''
RELATIVE_FOLDER_TO_UPLOAD_URL = ''

TRANS_FILTER_QS_SERIALIZER = {
    'laytime_details.shippingdetail': ('laytime_details.functions.return_ship_detail', 'laytime_details.serializers.ShippingDetailSerializer')
}

TRANS_FILTER_QS_EXCEL_SERIALIZER = {
    'laytime_details.shippingdetail': ('laytime_details.functions.return_excel_ship_detail', 'laytime_details.serializers.ShippingExcelSerializer')
}

EXCEL_IMPORT_CONFIGS = {
    'mstbrmstock': {
        'id': 0
    },
    'mstbrmstockotherloc': {
        'id': 0
    },
    'mstbrmtargetsheet': {
        'id': 0
    },
}

WORKFLOW_MODEL_LIST = [
    'porequestuttam',
    'shippingdetail'
]

WORKFLOW_EMAIL_CONFIGS = {
    'laytime_details.shippingdetail': 'laytime_details.workflowmails.trigger_laytime_mails'
}

APPROVAL_GROUPS = ['admin', 'CPO', 'Director Operation', 'Head BRM', 'Head Chartering',
                   'Section Head BRM' ,'Unit Finance', 'CFO', 'CEO']

GROUP_WISE_STATUS_MAPPING = {
    # 'HR': ['Pending For Approval', 'Initiated', 'Approved'],
}

EXCEL_EXPORT_CONFIGS={
    'mstbrmstockotherloc': {
        'fields_to_exclude': ['created_date', 'last_updated_date']
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'